baseurl: /migratedb
remote_theme: pages-themes/minimal@v0.2.0
plugins:
    - jekyll-remote-theme
    - jekyll-redirect-from
whitelist:
    - jekyll-redirect-from
migratedbReleaseVersion: 0.3.0
migratedbApiMajorVersion: 1
title: MigrateDB
description: Database Migrations, Easy and Free.
