= Changelog

All notable changes to this project will be documented in this file.

The format is based on https://keepachangelog.com/en/1.0.0/[Keep a Changelog], and this project adheres to https://semver.org/spec/v2.0.0.html[Semantic Versioning].

NOTE: 🔥 = breaking change

== [Unreleased]

This is the initial release after forking from Flyway 7.15 (the "community" version, obviously) and applying all 8.x bug fixes up to commit 77bb799. Since the forked project has never published any test sources, test coverage may seem a little underwhelming.
It will get better in time.

This is an early access 0.x release, which means *everything* is subject to change.
Feedback is very welcome!

=== Added

* This changelog 😀
* Streaming for script resources.
* Support for cherry picking migration versions.
* Support for pattern-based ignored migration versions.
* Maven plugin for build-time class path scanning.
* Gradle plugin for build-time class path scanning.
* 🔥 Simplified configuration of extensions via setExtensionConfig() or text-based properties.
* Unit tests for most changed/refactored code, especially configuration-related stuff.
* A few integration tests for databases where a docker container is publicly available.
* Builds should now be reproducible.

=== Changed

* 🔥 Renamed occurrences of "Flyway" to "MigrateDb".
* 🔥 Changed package name from org.flywaydb to migratedb.
* 🔥 Runtime class path scanning replaced with build-time scanning.
* Moved built-in features (database types) back into core artifact.
* 🔥 Extensions now contribute features via the MigrateDbExtensions interface.
* 🔥 Promoted some internal API like DatabaseType to public API since the extension API exposed those types anyway.
* 🔥 The "symbolic" migration versions (current, latest, next) are no longer instances of MigrationVersion, they have been moved to the new TargetVersion.
* 🔥 You can no longer pass Long.MAX_VALUE to MigrationVersion.fromString() to receive LATEST.
* 🔥 MigrationInfo no longer implements Comparable.
* 🔥 MigrationInfoImpl no longer overrides Object.equals.
* 🔥 No longer try to invoke inaccessible constructors when instantiating a class by name.
* 🔥 Class path locations (e.g. "classpath:db/migrate") now expect index files generated by build-time scanners.
* Logging during MigrateDB execution is disabled by default, can be changed via "logger" configuration option.
* By default, logging outside of MigrateDB execution is silenced.
Can be changed by application code via Log.setDefaultLogSystem().
* Configuration code that is specific to command line stuff has been moved to CLI artifact.
* Updated some driver versions that ship with the CLI artifact.
* 🔥 CLI no longer bundles a whole JDK.
* Un-deprecated ignore***Migrations() configuration options.
* Converted README to Asciidoc.

=== Deprecated

* License key configuration option (you will never ever need one!)

=== Removed

* Notion of "community/enterprise/trial/teams/pro" versions.
* 🔥 Options and checks related to "teams-only" features.
* Advertisements and nag messages.
* 🔥 Brittle runtime class path scanning heuristics.
* 🔥 Side-effects caused by SPI jars on class path.
Extensions must be activated in configuration via useExtension().
* Dependencies on native libraries.
* Colored console output.
* Telemetry via "update check".
* 🔥 Maven plugin(s) for executing migrations, etc.
* 🔥 Gradle plugin(s) for executing migrations, etc.
* 🔥 Explicit support for log4j2 (just use its SLF4 binding?)
* 🔥 The "empty" migration version.

=== Fixed

* Custom logging configuration is now only active while MigrateDB actually executes and no longer mutates global state.
* No longer swallows InterruptedException without re-interrupting the current thread.

=== Security

No items.
