= Changelog

All notable changes to this project will be documented in this file.

The format is based on https://keepachangelog.com/en/1.0.0/[Keep a Changelog], and this project adheres to https://semver.org/spec/v2.0.0.html[Semantic Versioning].

NOTE: 🔥 = Breaking Change

== https://search.maven.org/artifact/de.unentscheidbar/migratedb-core/0.1.0/jar[0.2.0]

This is an early access 0.x release, which means *everything* is subject to change.
Feedback is very welcome!

=== Added

* Tests for CockroachDB v22.1.1
* Some parser tests.

=== Removed

* 🔥 Batch, dryRun and licenseKey configuration.

=== Fixed

* JdbcTableSchemaHistory.create() no longer ignores being interrupted.
* Bugs from Flyway 8.x up to commit 8c38d8ee.

== https://search.maven.org/artifact/de.unentscheidbar/migratedb-core/0.1.0/jar[0.1.0]

This is the initial release after forking from Flyway 7.15 (the "community" version, obviously) and applying all 8.x bug fixes up to commit 77bb799. Since the forked project has never published any test sources, test coverage may seem a little underwhelming.
It will get better with every following release.

This is an early access 0.x release, which means *everything* is subject to change.
Feedback is very welcome!

=== Added

* This changelog 😸
* Support for streaming script resources.
* Support for baseline migrations.
* Support for cherry-picking migration versions.
* Support for pattern-based ignored migration versions.
* Maven plugin for build-time class path scanning.
* Gradle plugin for build-time class path scanning.
* Unit tests for most changed/refactored code, especially configuration-related stuff.
* A few integration tests for databases where a docker container is publicly available.
* Instead of re-distributing JDBC drivers, the command line tool can help you download them from Maven Central via the new `download-drivers` subcommand.
* Command that converts an existing schema history table to MigrateDB.

=== Changed

* 🔥 Renamed ALL occurrences of "Flyway" to "MigrateDb" (and "flyway" to "migratedb") in both code and config.
* 🔥 Changed package name from org.flywaydb to migratedb.
* 🔥 The minimum JRE version is 11 (previous LTS).
* 🔥 Runtime class path scanning replaced with build-time scanning.
* Moved built-in features (database types) back into core artifact.
* 🔥 Extensions now contribute features via the MigrateDbExtensions interface.
* 🔥 Promoted some internal API like DatabaseType to public API since the extension API exposed those types anyway.
* 🔥 Classes that are not meant to be subclassed are final.
(Well, some of them)
* 🔥 Simplified configuration of extensions via setExtensionConfig() or text-based properties.
* 🔥 Renamed LoadableResource to Resource and changed the resource API.
* 🔥 The "symbolic" migration versions (current, latest, next) are no longer instances of MigrationVersion, they have been moved to the new TargetVersion.
* 🔥 You can no longer pass Long.MAX_VALUE to MigrationVersion.fromString() to receive LATEST.
* 🔥 MigrationInfo and AppliedMigration no longer implement Comparable.
* 🔥 MigrationInfoImpl no longer overrides Object.equals.
* 🔥 No longer tries to invoke inaccessible constructors when instantiating a class by name.
* 🔥 Class path locations (e.g. "classpath:db/migrate") now expect index files generated by build-time scanners.
* Logging during MigrateDB execution is disabled by default, can be changed via "logger" configuration option.
* Custom logging configuration is now only active while MigrateDB actually executes and no longer mutates global state.
Afaik there is no mutable global state in the library now.
* By default, logging outside MigrateDB execution is silenced.
Can be changed by application code via Log.setDefaultLogSystem().
* Configuration code that is specific to command line stuff has been moved to CLI artifact.
* 🔥 Built-in script placeholder migratedb:timestamp now formatted as ISO-8601 instant.
* Updated some driver versions that ship with the CLI artifact.
* 🔥 CLI no longer bundles a whole JDK.
* Un-deprecated ignoreXXXMigrations() configuration options.
* 🔥 When the repair command marks migrations as deleted it no longer inserts an extra row into the schema history table.
If the deleted migration re-appears, another repair will un-delete it.
* 🔥 Future migrations are no longer (?) marked as deleted by the repair command.
* 🔥 Some additional states of schema history corruption are now detected.
* 🔥 The checksum is now an SHA-256 hash instead of 4 bytes CRC32.
* Converted README to Asciidoc.
* Removed a compile-time dependency on Oracle JDBC driver classes from the core library.
* Builds should now be reproducible.

=== Deprecated

* License key configuration option (you will never ever need one!)

=== Removed

* Notion of "community/enterprise/trial/teams/pro" versions.
* 🔥 Options and checks related to some "teams-only" features that haven't been implemented (notably undo migrations).
* Advertisements and nag messages.
* 🔥 Brittle runtime class path scanning heuristics.
* 🔥 Side effects caused by SPI jars on class path.
Extensions must be activated in configuration via useExtension().
* Dependencies on native libraries along with colored console output.
* Telemetry via "update check".
* 🔥 Maven plugin(s) for executing migrations, etc.
* 🔥 Gradle plugin(s) for executing migrations, etc.
* 🔥 Explicit support for log4j2 (just use its SLF4J binding?).
* 🔥 The "empty" migration version.
* 🔥 Support for wildcards in `filesystem:` locations.
* 🔥 InsertRowLock because of the deadlocks it caused.
* 🔥 Raw type usage.
* 🔥 StatementInterceptor.

=== Fixed

* No longer swallows InterruptedException without re-interrupting the current thread.
* JDBC connection leaks that were possible in certain situations.

=== Security

No items.
