= https://daniel-huss.github.io/migratedb[MigrateDB]

image:https://img.shields.io/badge/license-Apache%20License%202.0-blue.svg?style=flat[License,link=http://www.apache.org/licenses/LICENSE-2.0]
image:https://img.shields.io/maven-central/v/de.unentscheidbar/migratedb-core.svg?label=Maven%20Central&style=flat[Maven Central,link=https://mvnrepository.com/artifact/de.unentscheidbar/migratedb-core/1.0.0]

== Database Migrations, Easy and Free

Evolve your database schema easily and reliably across all your instances.

=== Supported databases

Oracle, SQL Server, MySQL, MariaDB, PostgreSQL, CockroachDB, Informix, H2, HSQLDB, Derby, SQLite, Firebird

Implemented, but currently not testable:

- DB2 (container does not work with podman)
- SAP HANA (no container available)
- Snowflake (no container available)
- Spanner (no container available)
- Synapse (no container available)
- Sybase ASE (no container available)
- Redshift (no container available)
- YugabyteDB (no container available)
- TiDB (no container available)
- Apache Ignite (JDBC driver only works on ancient Hotspot JVMs)

== Documentation

https://daniel-huss.github.io/migratedb[Website],
xref:CHANGELOG.adoc[Changelog],
https://daniel-huss.github.io/migratedb/documentation/contribute[How to contribute]

xref:migratedb-spring-boot-v3/README.adoc[See here if you're using Spring Boot]

== Support

The main priority of this project is to provide a bloat-free library for database migrations.
Bugs will be fixed, and new software versions will be supported as long as the changes are testable.
New features must fit reasonably within the scope of a database schema migration _library_, and have to be useful to
a large number (>1) of users 😉

=== Build Prerequisites

- Java 11 or later.
- Maven 3 (preferably the latest version)
- Local or remote Docker/Podman host (for database containers during integration tests)

== Legacy

This project is a hard fork of Flyway 7.15. There is no affiliation whatsoever between this project and the owners of the Flyway trademark.

Bug fixes from the forked project have been ported manually up to commit 8c38d8ee (2022-06-16 17:02:00)

=== Switching from Flyway to MigrateDB

https://daniel-huss.github.io/migratedb/documentation/switch[See instructions].

== License

Copyright (C) Red Gate Software Ltd 2010-2021 +
Copyright 2022-2023 The MigrateDB contributors

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.

== MigrateDB Contributors

In alphabetical order:

|===
|Name |GPG Key Fingerprint

|Daniel Huss
|7DF871E08AA9A9005514E44D8F6800C3B4CCDA0A
|===
