#!/usr/bin/env bash
#
# Copyright (C) Red Gate Software Ltd 2010-2021
# Copyright 2022-2023 The MigrateDB contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Dereference softlinks
THIS="$0"
 while [ -h "$THIS" ] ; do
  ls=$(ls -ld "$THIS")
  softlink=$(expr "$ls" : '.*-> \(.*\)$')
  if expr "$softlink" : '/.*' > /dev/null; then THIS="$softlink"; else THIS=$(dirname "$THIS")/"$softlink"; fi
 done
# Detect the installation directory
INSTALLDIR=$(dirname "$THIS")

if [ -x "$INSTALLDIR/jre/bin/java" ]; then
 JAVA_CMD=$INSTALLDIR/jre/bin/java
else
 # Use JAVA_HOME if it is set
 if [ -z "$JAVA_HOME" ]; then JAVA_CMD=java; else JAVA_CMD=$JAVA_HOME/bin/java; fi
fi

CP="$CLASSPATH:$INSTALLDIR/lib/*:$INSTALLDIR/drivers/*"

if $(command -v cygpath > /dev/null); then CP=$(cygpath -pw "$CP"); fi
# shellcheck disable=SC2086
exec "$JAVA_CMD" $JAVA_ARGS -cp "$CP" migratedb.v1.commandline.Main "-baseDirectory=$INSTALLDIR" "$@"
